[package]
name = "mlin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.65.1"

[dependencies]
libc = "0.2.147"
tinyvec = { version = "1.6.0", features = [ "alloc" ] }
